### ISSUE TITLE
Add caching provider support

### ISSUE THREAD

**Issue by sdnakhla** [doanduyhai/Achilles#189]
Adding the ability to configure a cache provider -- ehCache, Infinispan, etc. -- would greatly improve read performance when using this library.  I know that most JPA providers support it, and non-relational mapping libraries such as Kundera also support it.  It would be a welcome addition!

**Comment by doanduyhai** [comment]
Hello

 Can you give an example of use-case requiring an external cache manager ?

 When designing Achilles I avoided first level cache (as opposed to Hibernate) because I didn't want to pull in a class of complexity (cache invalidation, reference counting ...) to Achilles

The read performance of Achilles is directly related to the read performance of Cassandra.

Integrating Achilles with an external cache manager will make the read/write path more complex. What if the cache is down ? How and when should Achilles invalidate the cache ?

Let's keep the framework simple and avoid the temptation to make it as complex as Hibernate

**Comment by sdnakhla** [comment]
Cassandra is naturally write-oriented, in terms of speed.  Anything that may be read-heavy could benefit from a caching layer.  Since most web applications these days are read-heavy, there are a lot of valid use cases for such a component.  Web analytics and apps like that certainly wouldn't benefit, but that is because they are more write-intensive.

**Comment by doanduyhai** [comment]
I understand the use-case but in this case, you could write your own **[Interceptors]** to push data into a cache layer.

 It's not the responsibility of an object mapper to take care of the caching for you, simple principle of separation of concerns. There are enough extension points with interceptors so anyone could easily implement a bridge to a distributed cache

[Interceptors]: https://github.com/doanduyhai/Achilles/wiki/Interceptors#introduction
