### ISSUE TITLE
Cannot install achilles in OSGI environment (Servicemix 5.4.0) due to duplicate package info.archinnov.achilles.type

### ISSUE THREAD

**Issue by amorillotraxens** [doanduyhai/Achilles#217]
The package info.archinnov.achilles.type is exported by achilles-cores AND achilles-model. See the Export-package property in the MANIFEST.MF in both jars.
When starting the achilles-core bundle, the error is :
Error executing command: Error starting bundles:
        Unable to start bundle 1021: Uses constraint violation. Unable to resolve bundle revision info.archinnov.achilles-core [1021.0] because it exports package 'info.archinnov.achilles.type' and is also exposed to it from bundle revision info.archinnov.achilles-model [1023.0] via the following dependency chain:

  info.archinnov.achilles-core [1021.0]
    import: (&(osgi.wiring.package=info.archinnov.achilles.exception)(version>=3.2.0)(!(version>=4.0.0)))
     |
    export: osgi.wiring.package=info.archinnov.achilles.exception; uses:=info.archinnov.achilles.type
    export: osgi.wiring.package=info.archinnov.achilles.type
  info.archinnov.achilles-model [1023.0]

**Comment by doanduyhai** [comment]
Ok I got it.

Indeed the package `info.archinnov.achilles.type` is present both in **achilles-model** and **achilles-core**. Why ?

The package `info.archinnov.achilles.type` is supposed to contain public Java classes exposed by Achilles, like `InsertStrategy`, `Counter`...

Why can't we merge them in one module rather than in 2 different modules ? Because the classes in module **achilles-core** are dependent on the **java driver** classes whereas classes in the module **achilles-model** has 0 external dependency (that was the purpose of this module)

Solution ? Move the current classes in the **achilles-core** module to the **achilles-model** module:
1. `Empty`
2. `IndexCondition`
3. `IndexRelation`

Rename the existing `info.archinnov.achilles.type` package in the **achilles-core** module to `info.archinnov.achilles.options` 

Again, it'll be done in the release next week

**Comment by doanduyhai** [comment]
Fixed in Achilles 3.2.2
