### ISSUE TITLE
version 3.2.x( 3.2.3 as latest) not compatible with cassandra drives 2.1.6 and 2.1.7

### ISSUE THREAD

**Issue by maksimlikharev** [doanduyhai/Achilles#229]
2.1.7 is important as provides support of Enums in the accessor

**Comment by doanduyhai** [comment]
1. Do you know that Achilles 3.2.x does support enum via `@Enumerated` annotation ?
2. Latest version of Achilles is 4.0.0 and it is pulling Java driver 2.2.0-rc3, why don't you upgrade ?

**Comment by maksimlikharev** [comment]
1. I wasn't event there with enums, I just simply upgrade the driver and it stop working.
2. Latest version is incompatible with the code of 3.2.x, at least require code change( compilation errors )

**Comment by doanduyhai** [comment]
1. Ok so the error you had is because Achilles Embedded is pulling Cassandra 2.1.x binaries that uses one version of Netty and the Java driver 2.1.7 is using another version of Netty. One simple solution is to use the shaded version of the Java driver here: http://datastax.github.io/java-driver/features/shaded_jar/

2. Latest version of **Achilles**, namely **4.0.0** is a **complete rewrite**. It is using annotation processor to generate **type safe** query DSL. More info on how to configure your IDE here: https://github.com/doanduyhai/Achilles/wiki/IDE-configuration

**Comment by itsjimbo** [comment]
Thanks for all the great work!  Just wondering as the datastax-java-driver is changing frequently do you plan on keeping pace and releasing a compatible Achilles for the release candidate 3.0.0-rc1?

FYI
I have tried Achilles 4.0.0 with datastax 3.0.0-beta1 and there some changes, figured even more change with the 3.0.0-rc1 release.  Just trying to approximate a time.
https://datastax.github.io/java-driver/changelog/

**Comment by doanduyhai** [comment]
Next Achilles 4.x minor release will support Datastax Java driver 3.0.0-rc1. They have introduced some API breaking changes in the early iteration of the 3.x line so I need to update Achilles accordingly

**Comment by doanduyhai** [comment]
Fixed by **Achilles 4.1.0** release
