### ISSUE TITLE
Prepare statement support for (col1, col2) IN ((a1, b1), (a2, b2), (a3, b3))

### ISSUE THREAD

**Issue by kaicao** [doanduyhai/Achilles#238]
Hi, 
I'm being using Achilles since Cassandra 2.0 and really like it. But recently encounter an issue I can't get around without help from you.

The issue comes when I try to select * from table where pk1 = p1 and (col1, col2) IN(?), when using prepared statement Cassandra driver would complain Codec support error for tuple etc. 
So instead I changed to use RegularStatement and use 
manager.query().typedQueryForSelect(
  session.newSimpleStatement("SELECT...");
);
but typedQueryForSelect with RegularStatement create PreparedStatement for each query and cache it in RuntimeEngine. Since the query is different from each execution the preparation of query quickly causing issue for Cassandra and LRU is full.

Would need help to point out other ways by using Achilles (like the typed query and future handling instead of have to use java driver). Or would ask to provide typedQueryForSelect(RegularStatement stat, boolean makePrepared) to control when to create prepared statement.

Thank you!

**Comment by doanduyhai** [comment]
**Achilles** does **not** support right now all the `(clustering1, clustering2, ... clusteringN) IN (?)` queries because we will need to use `TupleN` classes to ensure type safety.

For example, let's consider the following entity:

```java
@Table
public class MyEntity {
    @PartitionKey
    private Long id;

    @ClusteringColumn(1)
    private String type;

    @ClusteringColumn(2)
    private Date date;
}
```

If we support   `IN()` clauses for tuples of clustering columns, the API would be:

```java
manager
   .dsl()
   .select()
   ....
   .where()
   .id_Eq(10L)
   .type_And_Date_IN(Tuple2<String, Date> tuple)
   ....
```

 There are only 10 classes for tuple types support: `Tuple1` to `Tuple10`. If the user has 11 clustering columns in his table, we can no longer use tuple classes and thus looses **type safety**

<hr/>
 

> but typedQueryForSelect with RegularStatement create PreparedStatement for each query and cache it in RuntimeEngine. Since the query is different from each execution the preparation of query quickly causing issue for Cassandra and LRU is full.

**Achilles** prepares a new statement only if the **query string** changes. So in your case, if your query is always `select * from table where pk1 = p1 and (col1, col2) IN(?)`, **Achilles** will only prepare it **once**. Of course if you change your query every time, there is no magic, **Achilles** will prepare it every time.

One solution would be that you execute the query itself using the native Java driver **session** object and then call `T manager.mapFromRow(Row row)` to perform object mapping on the returned `Row` object.

**Comment by kaicao** [comment]
Thanks for your reply, will implement using Java driver then and consult the code of Achilles for mapping to entity object and handling request futures.
