### ISSUE TITLE
Auto generated files with Scala

### ISSUE THREAD

**Issue by nikedlab** [doanduyhai/Achilles#260]
Can it be issue with absent generated classes when used scala? I use Intellij Idea for development and it adjusted as described in wiki

**Comment by doanduyhai** [comment]
It depends on which Scala compiler you're using:

1) If using SBT, you need to manually trigger Achilles annotation processor `info.archinnov.achilles.internals.apt.processors.meta.AchillesProcessor`. How to ? read this: http://stackoverflow.com/questions/25623915/sbt-how-to-run-an-annotation-processing-plugin

2) If using Maven with the `scala-maven-compiler`, which is the easiest option now, a simple `mvn compile` will invoke Achilles processor

So I would recommend you to configure your project in IntelliJ as mixed project with a Maven `pom.xml` and java/scala source code. 

Otherwise, another option is to do a `mvn clean compile` on your Java entities to let Achilles generate the source codes and them import them into your Scala project. In this case it will add an extra step in your build process, not sure it's easier than option 2)
