### ISSUE TITLE
question for startup

### ISSUE THREAD

**Issue by publicocean0** [doanduyhai/Achilles#317]
hi
is there a way for mapping ManyToMany,ManyToOne,OneToMany? It seams Datastax Objectmapper can do it. 

what is the differences   ```
  final Batch batch = manager.createLoggedBatch();
        final UserEntity userProxy = manager.forUpdate(UserEntity.class, newParticipant);
        userProxy.getChatRooms().add(roomName);
        batch.update(userProxy);
        batch.endBatch();
```
and      ```
userProxy.getChatRooms().add(roomName);
        manager.update(userProxy);

```
there is a way for saving/reading inputstream?

**Comment by doanduyhai** [comment]
Humm, it looks like you're using an old version of Achilles. From Achilles 4.x proxies have been completely removed, we now use compile-time code generation for all the DSL and Managers

**Comment by publicocean0** [comment]
ah ok. Just for understanding better. 
1) I have to denormalize the schema . I can t  make as JPA where i can use nested pojo(except udt because that data is embedded). Right?
2)i  saw now i can use fulltext index and index on a specific field. But it is possible to create a index on multiple fields? Or anyway cassandra use also partial index also in a complex query(If i want seach in if x=a or y=b  and i have index in x and y ... cassandra is able to compose indexes for the search). If i set a JSON or a map in cassadra i can then search also property inside json or map using a normal select?
3) before to see dse search fulltext i thought to install lucene plugin inside server for complex indexed query. But now i have a doubt ... can have also a sense to install that plugin if cassandra permits fulltext search?

**Comment by doanduyhai** [comment]
> I can t make as JPA where i can use nested entity(except udt because that data is embedded). Right? I can set just foreign key for nested entity.

Forget everything about JPA. Cassandra is not a relational database so all the notions like foreign key constraints etc... don't exist. For one to many/many to one relationships, use Cassandra **clustering columns**

> But it is possible to create a index on multiple fields?

No, not possible. And only **`AND`** semantics is allowed for index composition, not possible to use **`OR`** semantics

> If i set a JSON or a map in cassadra i can then search also property inside json or map using a normal select?

You can if you use DSE Search (because it implements Solr/Lucene underneath), with native Cassandra index or SASI index it's not possible

> Then i can define a index unique or not?

By default an index is defined on a **column of a table**. And there can be only **one index per column** so indeed index is unique per column

> before to see dse search fulltext i thought to install lucene plugin inside server for complex indexed query. But now i have a doubt ... still have also a sense to install that plugin if cassandra permits fulltext search? Maybe it depends by answer 2.... if cassandra permits to compose a multiple indexes on different fields or not.

Stratio lucene index will allow you to compose indices, so is DSE Search. The only thing is that right now **Achilles** only supports native Cassandra index, SASI index and DSE Search, not Stratio index
 
> Can i set as property a InputStream?how can i pass a stream of binary data?Or a way for saving a stream?

No, **`InputStream`** is **not** a supported type. Cassandra only support `blob`
 (**`ByteBuffer`** in Java) as data type. Additionally **Achilles** also support **`byte[]`** as data type for convenience but not **`InputStream`**. If you want to use **`InputStream`** as a property of your entity, consider using **[Codec System]** to transform your **`InputStream`** into **`ByteBuffer`**

> I see now also cassandra created a object mapper. Achilles will be merged with that ORM or not? Comparing Achilles and Dastastax are very similar .... but less features above all DDL generation is not present.

Maybe one day, if I can convince people from Datastax driver team. **Achilles** is just using the Java driver and offers much more than the Datastax mapper.


[Codec System]: https://github.com/doanduyhai/Achilles/wiki/Codec-System

**Comment by publicocean0** [comment]
Thanks for clarifications. You are kind. You are young but you are a very good developer. 
I want pass to Cassandra because i worked before in Orientdb (another no sql db for long time) but there are many problems and bugs in Orientdb . Tired for this situations. i want pass all my systems to Cassandra. I think there is no other choise for multimaster-distributed nosql database.
DSE seams not for community version. I need to pay license for enterprise i think. So unique way is to use stratio index

**Comment by publicocean0** [comment]
Eventually could fork your project or make a pull request for adding in future other features as 
- custom index on opensource stratio
- unique contraint on property
- inputstream management
