### ISSUE TITLE
Optimistic Locking support

### ISSUE THREAD

**Issue by jeanouii** [doanduyhai/Achilles#319]
In addition to the Lightweight transaction support, it would be pretty convenient to have a built-in support of Optimistic Locking.

Basically add a version field to the entity with an annotation in addition to the usual @Column.
Achilles would automatically handle the +1 on the version and add the IF version = xx in the update or delete statements.

What do you think?

**Comment by doanduyhai** [comment]
No way, it's too magical. **Achilles** should not become yet-another-Hibernate. Especially IF (LWT) has a huge cost in term of performance and should always be opt-in, not automagically enabled by the framework

**Comment by jeanouii** [comment]
Thanks for the fast answer.

**Comment by rmannibucau** [comment]
@doanduyhai any hope it gets enabled by achilles? like supporting a SPI which can contribute to the model (ddl) and some lifecycle hook without having the user to define it?

**Comment by doanduyhai** [comment]
No, **Achilles** philosophy is to avoid magic. That's the main purpose of Query DSL, the users how exactly which query is being sent to the server

**Comment by rmannibucau** [comment]
Hmm, this is actually not true since Achilles allows interceptors to be setup. What it doesn't allow is to deduce custom interceptors or enhance queries from the model. The optimistic locking is just a particular kind of LWT in term of implementation so it is exactly at the level where Achille is from my point of view.
